import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=AddPageShareSettings` — diff of
 * the entities against ./data/app.db. Hand-amended after generation:
 *   - UP: backfill of legacy poster titles from page_settings JSON
 *   - DOWN: replaced with a plain DROP — TypeORM's generated down for the
 *     SQLite table-recreate pattern is not executable as emitted.
 */
export class AddPageShareSettings1787932935957 implements MigrationInterface {
  name = 'AddPageShareSettings1787932935957'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
  'CREATE TABLE "page_share_settings" ("page_id" integer PRIMARY KEY NOT NULL, "title" text NOT NULL DEFAULT (\'\'), "font_size" integer NOT NULL DEFAULT (60), "width" integer NOT NULL DEFAULT (480), "height" integer NOT NULL DEFAULT (680), "border_width" integer NOT NULL DEFAULT (0), "border_radius" integer NOT NULL DEFAULT (12), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))',
  'CREATE TABLE "temporary_page_share_settings" ("page_id" integer PRIMARY KEY NOT NULL, "title" text NOT NULL DEFAULT (\'\'), "font_size" integer NOT NULL DEFAULT (60), "width" integer NOT NULL DEFAULT (480), "height" integer NOT NULL DEFAULT (680), "border_width" integer NOT NULL DEFAULT (0), "border_radius" integer NOT NULL DEFAULT (12), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "fk_page_share_settings_page" FOREIGN KEY ("page_id") REFERENCES "pages" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)',
  'INSERT INTO "temporary_page_share_settings"("page_id", "title", "font_size", "width", "height", "border_width", "border_radius", "updated_at") SELECT "page_id", "title", "font_size", "width", "height", "border_width", "border_radius", "updated_at" FROM "page_share_settings"',
  'DROP TABLE "page_share_settings"',
  'ALTER TABLE "temporary_page_share_settings" RENAME TO "page_share_settings"',
  'INSERT INTO "page_share_settings" ("page_id", "title") SELECT "page_id", COALESCE(CASE WHEN json_valid("config") THEN json_extract("config", \'$.share.posterTitle\') END, \'\') FROM "page_settings"',
]

const DOWN: string[] = ['DROP TABLE "page_share_settings"']
